export const popular: string[] = [
  "Home Alone",
  "Home Alone 2",
  "Elf",
  "National Lampoon's Christmas Vacation",
  "A Madea Christmas",
  "The Christmas Chronicles",
  "Christmas on the Square",
  "A Christmas Story",
  "It's a Wonderful Life",
  "Northpole",
];
export const romcom: string[] = [
  "Something from Tiffany's",
  "Falling for Christmas",
  "The Noel Diary",
  "Hot Frosty",
  "The Merry Gentlemen",
  "The Holiday",
  "Last Christmas",
  "A Castle for Christmas",
  "A Princess for Christmas",
  "A Prince for Christmas",
  //   "Christmas on the Square",
  //   "Northpole",
  //   "I'm not ready for Christmas",
  //   "Last Holiday",
  //   "The Christmas Chronicles",
];
export const classics: string[] = [
  "White Christmas",
  "Holiday Inn",
  "Miracle on 34th Street",
  "A Christmas Story",
  "It's a Wonderful Life",
  "National Lampoon's Christmas Vacation",
];
export const family: string[] = [
  "Trolls Holiday",
  "Rudolph the Red-Nosed Reindeer",
  "Frosty the Snowman",
  "Santa Clause",
  "Santa Clause 2",
  "Elf",
  "A Christmas Carol",
  "The Grinch",
  "A Charlie Brown Christmas",
  "Polar Express",
];
